print(string.lower('HeLlO'), string.upper('HeLlO'))
print(string.rep('x', 5))
print(string.len('hello' .. 'world'))
print(string.byte('hello'))
print(string.byte('hello', 2))
print(string.byte('hello', 2, 4))
print(string.sub('hello', 2, 4))
